name: Setup Image Tag
description: Generates a unique image tag based on branch, date, and run number

outputs:
  image-tag:
    description: "Computed image tag"
    value: ${{ steps.set-tag.outputs.image_tag }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Compute tag
      id: set-tag
      shell: bash
      run: |
        DATE=$(date +%Y%m%d)
        RUN_ID=${{ github.run_number }}
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          PR_NUMBER=${{ github.event.pull_request.number }}
          TAG="PR${PR_NUMBER}-${DATE}.run${RUN_ID}"
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          TAG="main-${DATE}.run${RUN_ID}"
        else
          BRANCH=$(echo "${{ github.ref }}" | sed 's|refs/heads/||' | sed 's|/|-|g' | tr '[:upper:]' '[:lower:]')
          TAG="${BRANCH}-${DATE}.run${RUN_ID}"
        fi
        
        echo "Generated tag: $TAG"
        echo "image_tag=$TAG" >> $GITHUB_OUTPUT
