name:  

inputs:
  version:
    description: 'Docker image version to scan'
    required: true
    type: string
    default: 'latest'
  token:
    required: true
    type: string
  severity:
    required: false
    type: string
    default: 'CRITICAL,HIGH'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    
    # This step will change the repository name to lowercase
    - name: Convert repository name to lowercase
      shell: bash
      id: repo
      run: |
        repo_lower=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
        echo "repo=$repo_lower" >> $GITHUB_OUTPUT

    # Install and scan using Trivy
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ steps.repo.outputs.repo }}:${{ inputs.version }}
        format: table
        exit-code: 0
        output: trivy-report.txt
        vuln-type: os,library
        severity: ${{ inputs.severity }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    # Upload the Trivy report as an artifact
    - name: Trivy Summary
      shell: bash
      run: |
        CRITICAL=$(grep -c 'CRITICAL' trivy-report.txt || true)
        HIGH=$(grep -c 'HIGH' trivy-report.txt || true)

        echo "## ðŸ›¡ï¸ Trivy Scan" >> $GITHUB_STEP_SUMMARY
        echo "- ðŸš¨ Critical: $CRITICAL" >> $GITHUB_STEP_SUMMARY
        echo "- âš ï¸ High: $HIGH" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "<details><summary>ðŸ“„ View Raw Report (truncated)</summary>" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        head -n 100 trivy-report.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY
