name: "Python Linter"
description: "Run linter on Python files"

inputs:
  lint-command:
    description: "Command to execute Pylint"
    required: false
    default: "pylint $(git ls-files '*.py')"
  continue-on-error:
    description: "Continue on error"
    required: false
    default: 'true'


runs:
  using: "composite"
  steps:
    - name: Run Pylint continue on error
      if: inputs.continue-on-error == 'true' 
      shell: bash
      continue-on-error: true
      run: |
        ${{ inputs.lint-command }}
    - name: Run Pylint fail on error
      if: inputs.continue-on-error != 'true' 
      shell: bash
      run: |
        ${{ inputs.lint-command }}
