on:
  workflow_call:
    outputs:
      image-tag:
        description: "Computed image tag"
        value: ${{ jobs.setup.outputs.image_tag }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}
    steps:
      - name: Compute tag
        id: set-tag
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          BRANCH_LOWER=$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          DATE=$(date +%Y%m%d)
          TAG="${BRANCH_LOWER}-${DATE}.${{ github.run_number }}"
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT